### ISSUE TITLE
Support file lists through pipeline

### ISSUE THREAD

**Issue by sk22** [itchyny/mmv#14]
i would like to be abole to use `find` or any other command that generates a file list along with `mmv`, for example:

```sh
find . -type f -name "what*ever" | mmv
```

using `xargs mmv` works, but i don't think this is ideal as it might run into problems with spaces in file names, and also `xargs` doesn't exist on windows (i think?)

thanks - and thanks for this great program!

**Comment by itchyny** [comment]
`mmv "$(find . -type f)"` works for me for path with spaces

**Comment by itchyny** [comment]
Using `-print0` is the general solution to take care of spaces with `find` and `xargs`. I don't like accepting stdin because it can be infinite stream so exhaust the memory unless I have to limit with some unconfident count.

**Comment by sk22** [comment]
oh okay. thanks!
