### ISSUE TITLE
Tips for extensive usage

### ISSUE THREAD

**Issue by tkkcc** [itchyny/mmv#15]
I have trouble relinking multiple symlinks after the destination locations change. In order to correct these symlinks, I have to recreate them one by one. I want to use mmv as a helper for this task. Do you have any suggestion.

**Comment by itchyny** [comment]
This tool does not follow symlinks. This tool runs essentially a sequence of mv and nothing else. Changing the symlink target is out of the scope of this tool. Moreover, we cannot fix the symlinks outside of the arguments.
