### ISSUE TITLE
Feature: Be nice if mmv defaulted to mmv *

### ISSUE THREAD

**Issue by joshpetit** [itchyny/mmv#17]
So if someone typed `mmv` it would open up all the files in the directory to be renamed.

I love this tool, could never get used to most cli file managers and this is a feature a lot of them have that I like.

**Comment by itchyny** [comment]
I don't think this is a good default. Specifying the target is important for this tool and typing [space]* is not such painful.

Use a command wrapper if you still need the feature.
```bash
mmv() {
  if [ $# -gt 0 ]; then
    command mmv "$@"
  else
    command mmv ./*
  fi
}
```
