### ISSUE TITLE
A flag to perform `git mv`

### ISSUE THREAD

**Issue by kovmir** [itchyny/mmv#18]
It would be great to be able to invoke `mmv --git` to perform `git mv` instead of traditional renaming.

**Comment by itchyny** [comment]
The goal of this tool is simplicity that just executes multiple file moves. Relying another command grows the dependency and brings complexity. This is a duplicate of #12, and still unlikely to support in this project.

**Comment by kovmir** [comment]
FYI and #12: I have discovered, it is achievable without additional contributions to `mmv`. Simply rename the files, and then stage both the new, and deleted ones. `git` is smart enough to interpret this as a rename.
