### ISSUE TITLE
Rename in empty folder gives `*` to rename

### ISSUE THREAD

**Issue by kpym** [itchyny/mmv#21]
When we try to rename the files in an empty folder with `mmv *`, we get a file with a single asterisk as content instead of an empty file.

**Comment by itchyny** [comment]
Glob expansion is done by shell, not by commands. This is how other commands works.
```sh
 $ cd $(mktemp -d)
 $ ls *
"*": No such file or directory (os error 2)
 $ mv * /tmp
mv: rename * to /tmp/*: No such file or directory
```
If you don't like this behavior, use `CSH_NULL_GLOB` on zsh, or `nullglob` on bash.
```sh
 $ setopt CSH_NULL_GLOB
 $ ls *
zsh: no match
 $ mv * /tmp
zsh: no match
 $ mmv *
zsh: no match
```

**Comment by kpym** [comment]
I may have been unclear in my request: for me this is not a bug but a feature request. 

It seems simpler and more user friendly to me that `mmv` checks if the generated file is `*` or `.` and replaces it with an empty file.
_(Normally the generated file should not contain `*` and should not have `.` as a line.)_

Anyway, thanks for your software.

**Comment by itchyny** [comment]
I think the current behavior is fine. While `.` itself is not a valid file name, `*` is a valid filename. mmv respects its argument strictly, and a user may actually want to rename a file named `*`. The mv command tries to rename the `*` file and that's why it prints `No such file or directory`.

**Comment by kpym** [comment]
ok it's up to you ;)

**Comment by itchyny** [comment]
Sorry I can't help you. I'd suggest using a command wrapper.
```sh
mmv() {
  if [[ "$*" == "*" ]]; then
    echo "mmv: invalid argument: $*" >&2
    exit 1
  else
    command mmv "$@"
  fi
}
```
